CREATE TABLESPACE  PROJETO_BD_FATEC
DATAFILE  'D:\BD\PROJETO_BD_FATEC.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER PROJETO
IDENTIFIED BY aluno
DEFAULT TABLESPACE PROJETO_BD_FATEC
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON PROJETO_BD_FATEC;

GRANT DBA TO PROEJETO WITH ADMIN OPTION;
