insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (1, 'Lars', 'lduly0@nhs.uk', 'IW2FE0fhanib', 'Lars Duly', 'http://dummyimage.com/117x175.bmp/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (2, 'Killy', 'kkinlock1@cnet.com', '7DuM8gRz6wQ', 'Killy Kinlock', 'http://dummyimage.com/216x158.jpg/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (3, 'Katti', 'kbrigman2@artisteer.com', 'BSFyp2zrBlhl', 'Katti Brigman', 'http://dummyimage.com/247x157.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (4, 'Etta', 'ebuddles3@scribd.com', 'bMQb3IPYYtk', 'Etta Buddles', 'http://dummyimage.com/144x196.png/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (5, 'Rudolf', 'rtesimon4@loc.gov', 'gwDG1zp9Gk', 'Rudolf Tesimon', 'http://dummyimage.com/224x133.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (6, 'Ferguson', 'fandri5@facebook.com', '2zXWzoFit', 'Ferguson Andri', 'http://dummyimage.com/230x153.jpg/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (7, 'Cullan', 'cabrehart6@theglobeandmail.com', 'UDMsSpm7v', 'Cullan Abrehart', 'http://dummyimage.com/196x194.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (8, 'Corri', 'chedgecock7@home.pl', 'UM8SeyGD2u8', 'Corri Hedgecock', 'http://dummyimage.com/239x126.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (9, 'Cherye', 'csanbrook8@tiny.cc', 'LwjDY4Q', 'Cherye Sanbrook', 'http://dummyimage.com/130x115.jpg/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (10, 'Hendrika', 'hwittrington9@columbia.edu', 'ib7aBlb1uO2', 'Hendrika Wittrington', 'http://dummyimage.com/160x242.bmp/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (11, 'Carey', 'cdea@example.com', 'rR9wPTzJ', 'Carey De Luna', 'http://dummyimage.com/183x231.jpg/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (12, 'Bonni', 'bkitherb@jugem.jp', 'cVZhOWM', 'Bonni Kither', 'http://dummyimage.com/128x224.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (13, 'Laureen', 'lcettellc@geocities.com', 'J7KfLIKhq', 'Laureen Cettell', 'http://dummyimage.com/206x179.png/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (14, 'Delia', 'dmelanaphyd@netscape.com', 'hNzUa8lvb', 'Delia Melanaphy', 'http://dummyimage.com/200x217.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (15, 'Mozes', 'mwildene@ihg.com', '8GlnEqdnD', 'Mozes Wilden', 'http://dummyimage.com/100x209.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (16, 'Rheta', 'rrosenf@psu.edu', '5Io1oTTQ', 'Rheta Rosen', 'http://dummyimage.com/157x160.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (17, 'Lucia', 'lpavolinig@technorati.com', 'W8bmQxNVuh', 'Lucia Pavolini', 'http://dummyimage.com/247x147.bmp/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (18, 'Nat', 'ngumbyh@psu.edu', 'HQzvnUde4x', 'Nat Gumby', 'http://dummyimage.com/141x159.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (19, 'Ferdie', 'fbuntingi@imdb.com', '8ggv7yHco92', 'Ferdie Bunting', 'http://dummyimage.com/101x111.png/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (20, 'Margaretha', 'mstrongmanj@nhs.uk', 'WIast7mHtj', 'Margaretha Strongman', 'http://dummyimage.com/174x228.png/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (21, 'Udall', 'udukelowk@ehow.com', 'yqQSarwJ1J', 'Udall Dukelow', 'http://dummyimage.com/239x135.bmp/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (22, 'Denny', 'drastalll@gov.uk', 'hl1PsX7i17k', 'Denny Rastall', 'http://dummyimage.com/178x227.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (23, 'Genna', 'gpresnailm@marketwatch.com', 'mdWAeE', 'Genna Presnail', 'http://dummyimage.com/234x181.png/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (24, 'Margarethe', 'mwyken@shinystat.com', 'YBSjts3Grcya', 'Margarethe Wyke', 'http://dummyimage.com/172x141.bmp/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (25, 'Arlyne', 'ameaseo@zimbio.com', '66nAeMwa8j', 'Arlyne Mease', 'http://dummyimage.com/104x120.png/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (26, 'Alta', 'asimoensp@princeton.edu', '7TlrmL7', 'Alta Simoens', 'http://dummyimage.com/199x183.jpg/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (27, 'Shelley', 'skringeq@phoca.cz', 'VJcsAX6', 'Shelley Kringe', 'http://dummyimage.com/218x167.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (28, 'Ronnie', 'rruder@clickbank.net', '7q5q76', 'Ronnie Rude', 'http://dummyimage.com/244x140.jpg/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (29, 'Trista', 'thazlewoods@seesaa.net', 's6PaCd39hkrs', 'Trista Hazlewood', 'http://dummyimage.com/136x198.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (30, 'Saudra', 'sknellent@cbslocal.com', 'GsRkMHj', 'Saudra Knellen', 'http://dummyimage.com/127x203.bmp/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (31, 'Guillemette', 'gbotfieldu@theguardian.com', 'oKygV9', 'Guillemette Botfield', 'http://dummyimage.com/206x211.png/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (32, 'Conny', 'cberendsv@fda.gov', 'evZzlp5c', 'Conny Berends', 'http://dummyimage.com/178x197.jpg/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (33, 'Alysia', 'asaunderw@ezinearticles.com', 'CjPwUnVXZRAH', 'Alysia Saunder', 'http://dummyimage.com/219x239.bmp/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (34, 'Hephzibah', 'harnouldx@bbb.org', 'fyBLzcHNOp', 'Hephzibah Arnould', 'http://dummyimage.com/183x220.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (35, 'Rhys', 'ryersony@webs.com', 'u4MwB9', 'Rhys Yerson', 'http://dummyimage.com/223x194.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (36, 'Karlan', 'klamplughz@techcrunch.com', 'dULinbBG', 'Karlan Lamplugh', 'http://dummyimage.com/171x112.jpg/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (37, 'Xymenes', 'xatwell10@cafepress.com', 'wyTGXlc2', 'Xymenes Atwell', 'http://dummyimage.com/179x199.png/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (38, 'Poul', 'pbabcock11@simplemachines.org', 'Kka57D55Zl16', 'Poul Babcock', 'http://dummyimage.com/203x138.png/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (39, 'Chadd', 'cbitchener12@shareasale.com', 'KpivmH', 'Chadd Bitchener', 'http://dummyimage.com/186x207.png/dddddd/000000', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (40, 'Rudolfo', 'redelmann13@digg.com', '7bXrUV5uoG', 'Rudolfo Edelmann', 'http://dummyimage.com/179x214.jpg/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (41, 'Joycelin', 'jjanecki14@bloglines.com', 'ohfGM1snfi', 'Joycelin Janecki', 'http://dummyimage.com/128x220.jpg/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (42, 'Carleton', 'ckinahan15@engadget.com', 'nNamgjf5Xmc', 'Carleton Kinahan', 'http://dummyimage.com/232x146.jpg/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (43, 'Selig', 'sriddock16@tamu.edu', 'yjt3Y3uM', 'Selig Riddock', 'http://dummyimage.com/146x147.bmp/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (44, 'Yelena', 'ysommerfeld17@blogger.com', 'IzHQecl', 'Yelena Sommerfeld', 'http://dummyimage.com/124x236.bmp/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (45, 'Kerri', 'kgorst18@elpais.com', 'tOLwlZ', 'Kerri Gorst', 'http://dummyimage.com/210x159.jpg/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (46, 'Dorisa', 'dcampana19@amazon.co.uk', 'C8WYrVhBlV', 'Dorisa Campana', 'http://dummyimage.com/190x164.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (47, 'Karylin', 'kbiaggetti1a@4shared.com', 'iNblRjUUS', 'Karylin Biaggetti', 'http://dummyimage.com/248x240.png/cc0000/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (48, 'Inessa', 'iraise1b@gmpg.org', 'EEDRD59', 'Inessa Raise', 'http://dummyimage.com/151x202.jpg/ff4444/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (49, 'Paulo', 'pwitnall1c@statcounter.com', 'XHlmw90mfmg', 'Paulo Witnall', 'http://dummyimage.com/223x143.bmp/5fa2dd/ffffff', 'A');
insert into usuario (usu_codigo, usu_login, usu_email, usu_senha, usu_nome, usu_foto, usu_status) values (50, 'Kyrstin', 'ksills1d@tripadvisor.com', 'ScQwlUgat9', 'Kyrstin Sills', 'http://dummyimage.com/221x197.bmp/5fa2dd/ffffff', 'A');


insert into aluno (usu_codigo, alu_matricula) values (1, '67510-0633');
insert into aluno (usu_codigo, alu_matricula) values (2, '0699-1081');
insert into aluno (usu_codigo, alu_matricula) values (3, '66382-223');
insert into aluno (usu_codigo, alu_matricula) values (4, '55154-6775');
insert into aluno (usu_codigo, alu_matricula) values (5, '21695-851');
insert into aluno (usu_codigo, alu_matricula) values (6, '45014-139');
insert into aluno (usu_codigo, alu_matricula) values (7, '17478-101');
insert into aluno (usu_codigo, alu_matricula) values (8, '49999-878');
insert into aluno (usu_codigo, alu_matricula) values (9, '43353-771');
insert into aluno (usu_codigo, alu_matricula) values (10, '67684-1901');
insert into aluno (usu_codigo, alu_matricula) values (11, '68788-9782');
insert into aluno (usu_codigo, alu_matricula) values (12, '60760-059');
insert into aluno (usu_codigo, alu_matricula) values (13, '58668-4221');
insert into aluno (usu_codigo, alu_matricula) values (14, '53808-0356');
insert into aluno (usu_codigo, alu_matricula) values (15, '35356-593');
insert into aluno (usu_codigo, alu_matricula) values (16, '57664-167');
insert into aluno (usu_codigo, alu_matricula) values (17, '65862-556');
insert into aluno (usu_codigo, alu_matricula) values (18, '49035-851');
insert into aluno (usu_codigo, alu_matricula) values (19, '49349-478');
insert into aluno (usu_codigo, alu_matricula) values (20, '42787-102');
insert into aluno (usu_codigo, alu_matricula) values (21, '0085-1322');
insert into aluno (usu_codigo, alu_matricula) values (22, '54868-5023');
insert into aluno (usu_codigo, alu_matricula) values (23, '66949-252');
insert into aluno (usu_codigo, alu_matricula) values (24, '52125-933');
insert into aluno (usu_codigo, alu_matricula) values (25, '54868-4532');
insert into aluno (usu_codigo, alu_matricula) values (26, '51389-112');
insert into aluno (usu_codigo, alu_matricula) values (27, '0067-6716');
insert into aluno (usu_codigo, alu_matricula) values (28, '35418-136');
insert into aluno (usu_codigo, alu_matricula) values (29, '59316-205');
insert into aluno (usu_codigo, alu_matricula) values (30, '47335-046');
insert into aluno (usu_codigo, alu_matricula) values (31, '10812-146');
insert into aluno (usu_codigo, alu_matricula) values (32, '42507-431');
insert into aluno (usu_codigo, alu_matricula) values (33, '52125-018');
insert into aluno (usu_codigo, alu_matricula) values (34, '75874-701');
insert into aluno (usu_codigo, alu_matricula) values (35, '51138-076');
insert into aluno (usu_codigo, alu_matricula) values (36, '68258-3029');
insert into aluno (usu_codigo, alu_matricula) values (37, '49035-928');
insert into aluno (usu_codigo, alu_matricula) values (38, '10631-113');
insert into aluno (usu_codigo, alu_matricula) values (39, '49738-101');
insert into aluno (usu_codigo, alu_matricula) values (40, '41190-281');
insert into aluno (usu_codigo, alu_matricula) values (41, '59972-0106');
insert into aluno (usu_codigo, alu_matricula) values (42, '65044-3041');
insert into aluno (usu_codigo, alu_matricula) values (43, '37205-321');
insert into aluno (usu_codigo, alu_matricula) values (44, '63739-448');
insert into aluno (usu_codigo, alu_matricula) values (45, '17312-019');
insert into aluno (usu_codigo, alu_matricula) values (46, '48951-5007');
insert into aluno (usu_codigo, alu_matricula) values (47, '55154-6664');
insert into aluno (usu_codigo, alu_matricula) values (48, '59779-590');
insert into aluno (usu_codigo, alu_matricula) values (49, '63777-204');
insert into aluno (usu_codigo, alu_matricula) values (50, '49999-797');

