insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (1, 1, 'Apostila 1', 'Bacteremia', '/vel/ipsum/praesent/blandit/lacinia/erat.html', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (2, 2, 'Apostila 1', 'Gambling and betting', '/risus/auctor.aspx', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (3, 3, 'Apostila 1', 'Exfl d/t eryth 80-89 bdy', '/cras/non/velit/nec/nisi.js', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (4, 4, 'Apostila 1', 'Taeniasis NOS', '/eget/orci/vehicula/condimentum/curabitur/in/libero.aspx', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (5, 5, 'Apostila 1', 'Tubal ligation status', '/nisl/aenean/lectus/pellentesque/eget/nunc.aspx', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (6, 6, 'Apostila 1', 'Ob trauma NEC-del w p/p', '/sit/amet/eleifend/pede/libero/quis/orci.png', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (7, 7, 'Apostila 1', 'Cicatricial entropion', '/maecenas/ut/massa/quis/augue.jpg', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (8, 8, 'Apostila 1', 'Food pois: v. parahaem', '/a/libero/nam/dui/proin/leo.json', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (9, 9, 'Apostila 1', 'Venomous bite/sting NOS', '/ipsum/ac.png', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (10, 10, 'Apostila 1', 'Submers NEC-crew', '/vestibulum/proin/eu/mi/nulla/ac/enim.aspx', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (11, 11, 'Apostila 1', 'Ascending colon inj-open', '/quisque.js', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (13, 2, 'Apostila 2', 'Inf mcrg rstn sulfnmides', '/consequat/dui.xml', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (14, 5, 'Apostila 2', 'Ca in situ fem gen NEC', '/in/magna/bibendum/imperdiet.js', 'A');
insert into anexo (ANE_CODIGO, AUL_CODIGO, ANE_TITULO, ANE_COMENTARIO, ANE_LINK, ANE_STATUS) values (15, 13, 'Apostila 1', 'Cl skull fx NEC-brf coma', '/eu.html', 'A');
